### ISSUE TITLE
MSI installer failure on Windows 10

### ISSUE THREAD

**Issue by earthbound19** [atomex-me/atomex.client.desktop#1]
On attempt to install the current Windows desktop client I get from here:

https://atomex.me/

-- I get a dialog box with this error:

`Could not set file security for file C:\Users\<myusername>\AppData\Roaming\Microsoft\Installer\'. Error: 5. Verify that you have sufficient privileges to modify the security permissions for this file.`

-- and when I press the "OK" button, it exists (it failed to install).

I would think that nothing should be modifying the security permissions of that folder, and apparently something is attempting to.

**Comment by matsakiv** [comment]
I could be wrong, but the Microsoft Installer service always runs as SYSTEM and has administrator privileges.

It looks like the access privileges for "%APPDATA%\Roaming\Microsoft\Installer" folder have been changed. You need to check who has write access to this directory. 

Google also advises to check the rights to create files on the system disk and check free space on the system disk (for the TEMP folders that are used by the Microsoft Installer service). But, I'm sure that is not the case. It looks like your workstation has restrictions set by an administrator.

**Comment by earthbound19** [comment]
It would indeed seem this is a local permissions issue. If I run a `cmd` prompt as `nt authority\system` (I have tricks for doing that--a perhaps ultimate authority account), it installs fine, thanks. But that's a hacky solution and maybe I best fix the permissions issue :)

**Comment by earthbound19** [comment]
Addenda: weirdly, I found that this folder is empty in my user profile. Deleting the folder, then re-running the installer fixed it.
